import tool from '../utils/Tool'

export default {
  //修改基本信息
  addBaseInfo(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/addBaseInfo',
      data,
      success
    })
  },
  //修改求职意向
  addJobIntention(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/addJobIntention',
      data,
      success
    })
  },
  //修改或添加教育经历
  addEducations(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/addEducations',
      data,
      success
    })
  },
  //修改或添加工作经历
  addWorkExperiences(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/addWorkExperiences',
      data,
      success
    })
  },
  //修改或添加项目经历
  addProjects(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/addProjects',
      data,
      success
    })
  },
  //修改或添加掌握技能
  addProfeskills(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/addProfeskills',
      data,
      success
    })
  },
  //修改或添加自我评价
  updateSelfEvaluate(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/updateSelfEvaluate',
      data,
      success
    })
  },
  //上传图片
  uploadHeadImg(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/uploadHeadImg',
      data,
      success
    })
  },
  //获取简历详情
  getResumeDeatil(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/getResumeDeatil',
      data,
      success
    })
  },
  //根据id获取不同经历接口
  getExperience(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/getExperience',
      data,
      success
    })
  },
  //删除各种经历接口
  experienceDelete(data,success){
    tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/experienceDelete',
      data,
      success
    })
  },
  //获取完善度
  countType(success){
  	tool.ajax({
      url:tool.serviceUrl+'/resumeControllOperation/countType',
      success
    })
  },
  //添加培訓經歷
  addTrainings(data,success){
  	tool.ajax({
      data,
      url:tool.serviceUrl+'/resumeControllOperation/addTrainings',
      success
    })
  },
  //添加證書
  addCertificate(data,success){
  	tool.ajax({
      data,
      url:tool.serviceUrl+'/resumeControllOperation/addCertificate',
      success
    })
  }
};
